#if !canImport(ObjectiveC)
import XCTest

extension GitHubDecodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GitHubDecodingTests = [
        ("test_parsing_pull_request_event_context", test_parsing_pull_request_event_context),
    ]
}

extension GitHubEventsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GitHubEventsTests = [
        ("test_handling_ping_event", test_handling_ping_event),
        ("test_handling_pull_request_event", test_handling_pull_request_event),
        ("test_handling_unknown_event", test_handling_unknown_event),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GitHubDecodingTests.__allTests__GitHubDecodingTests),
        testCase(GitHubEventsTests.__allTests__GitHubEventsTests),
    ]
}
#endif
