#if !canImport(ObjectiveC)
import XCTest

extension LogsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LogsTests = [
        ("test_json_logs_formatting", test_json_logs_formatting),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LogsTests.__allTests__LogsTests),
    ]
}
#endif
